export const generateMatrixArray = size => {
    let arr = [];
    for (let row = 0; row < size; row++) {
        arr[row] = [];
        for (let col = 0; col < size; col++) {
            arr[row][col] = { x: col, y: row, hasShip: false, locked: false, className: "cell" };
        }
    }
    return arr;
};

export const cloneDeep = x => JSON.parse(JSON.stringify(x));

export const rndInt = (min, max) => {
    return Math.floor(Math.random() * (max - min + 1)) + min;
};

export const generateRandomCell = () => ({ x: rndInt(0, 9), y: rndInt(0, 9) });

export const generateRandomOrientation = () => (rndInt(0, 100) > 50 ? "HORIZONTAL" : "VERTICAL");

export const enemyField = [
    { x: 0, y: 0, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 1, y: 0, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 2, y: 0, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 3, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 0, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 9, y: 0, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 1, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 6, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 1, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 2, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 3, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 2, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 6, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 2, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 9, y: 2, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 3, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 9, y: 3, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 4, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 5, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 4, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 9, y: 4, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 5, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 1, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 5, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 5, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 5, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 6, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 8, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 6, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 7, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 1, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 2, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 3, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 4, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 8, hasShip: false, locked: false, className: "cell" },
    { x: 0, y: 9, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 1, y: 9, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 2, y: 9, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 3, y: 9, hasShip: true, locked: true, className: "cell-occupied" },
    { x: 4, y: 9, hasShip: false, locked: false, className: "cell" },
    { x: 5, y: 9, hasShip: false, locked: false, className: "cell" },
    { x: 6, y: 9, hasShip: false, locked: false, className: "cell" },
    { x: 7, y: 9, hasShip: false, locked: false, className: "cell" },
    { x: 8, y: 9, hasShip: false, locked: false, className: "cell" },
    { x: 9, y: 9, hasShip: false, locked: false, className: "cell" },
];
